version: "3"

services:

  server:
    container_name: serverNode
    restart: always
    build: .      # Dockerfile
    ports:
      - "5000:5000"
    links:
      - database
    volumes:
      - .:/usr/src/app

  database:
    container_name: "databaseMongo"
    image: mongo:latest
    ports:
      - "27020:27017"
    logging:  # Do not see logs
      driver: none
